### PR TITLE
Feat/online editing

### PR DESCRIPTION
**Pull request by John-Theo**

### CODE REVIEW

**Comment by John-Theo** [comment]
`.idea`s again.... this is f stupid, need .gitignore...

**Comment by John-Theo** [comment]
duplicate commit `add cache`

**Comment by awmleer** [comment]
Is this PR ready to merge? @John-Theo

**Comment by John-Theo** [comment]
> Is this PR ready to merge? @John-Theo

yes, it is

**Comment by John-Theo** [comment]
uh oh.. should not be closed...

**Pull request merged**
